name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv .venv
          source .venv/bin/activate
          pip install --upgrade -r requirements.txt

      - name: Show pip version and list
        run: |
          pip --version
          pip list --local

      - name: Check formatting
        run: |
          source .venv/bin/activate
          ruff format --check
          sort-requirements --check requirements.txt

      - name: Linting
        run: |
          source .venv/bin/activate
          mkdir -p public
          ruff check --output-format=github --output-file=public/ruff-report.json .

      - name: Run tests
        run: |
          source .venv/bin/activate
          mkdir -p public
          pytest weather/tests/ \
            --junitxml=public/pytest_report.xml \
            --html=public/pytest_report.html --self-contained-html \
            --cov=. --cov-report=xml --cov-report=html:public/coverage --cov-config=.coveragerc

      - name: Generate documentation
        run: |
          source .venv/bin/activate
          pdoc weather !weather.tests --output-dir public

      - name: Upload test and coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: public-artifacts
          path: public